Homework (2022-04-04) - Основы алгоритмов (ч2)
Lancoid/skypro-education-spring pull request #10
Opened 2022-04-09 16:19 UTC by Lancoid

- Выполнил домашнее задание по теме "Основы алгоритмов (часть 2)"

2022-04-10 12:18 UTC, OKrylov requested changes
В целом хорошая работа, но есть ряд замечаний по коду, на которые следует обратить внимание и поправить код.
Если будут вопросы - пишите!

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        ++listSize;
можно объединить
```suggestion
        data[listSize++] = item;
```

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        data[index] = item;
add работает здесь как и set, что некорректно. Мы должны выполнить сдвиг вправо на одну позицию всех элементов, начиная с index

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        int string = get(index);
некорректное имя переменной

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        System.arraycopy(data, index + 1, data, index, listSize);
почему мы делаем сдвиг в количестве listSize? Нам нужно сдвинуть влево только те элементы, что идут после index позиции, а их количество не всегда будет listSize

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        listSize--;
также есть смысл обнулить последний дублирующийся элемент после сдвига, чтобы сборщик мусора мог его обнулить
```suggestion
        data[listSize - 1] = null;
        listSize--;
```

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        this.data = new int[DEFAULT_CAPACITY];
не забываем обнулять listSize

2022-04-10 12:18 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        listCapacity += 1;
увеличивать размерность на единицу не оптимально, так как при каждом новом добавлении нам вновь придется создавать новый массив и копировать в него элементы из старого, что неэффективно. Лучше сразу увеличивать размерность в 1.5-2 раза

2022-04-10 12:18 UTC, OKrylov commented on src/test/java/com/company/skyproeducationspring/list/IntListUnitTest.java
> +        randomGenerator = (new Faker()).random();
faker удобно использовать для генерации случайной последовательности символов. В данном случае нам отлично подойдет клас Random

2022-04-10 12:20 UTC, OKrylov requested changes
В целом хорошая работа, но есть ряд замечаний по коду, на которые следует обратить внимание и поправить код.
Также отсутствует сравнительный код с тестом по выявлению лучше сортировки
Если будут вопросы - пишите!

2022-04-11 08:19 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        listCapacity += 1;
Исправил

2022-04-11 08:31 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        this.data = new int[DEFAULT_CAPACITY];
Исправил

2022-04-11 08:32 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        int string = get(index);
Исправил

2022-04-11 14:37 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        data[index] = item;
Исправил

2022-04-11 14:37 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        ++listSize;
Исправил

2022-04-11 16:14 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        System.arraycopy(data, index + 1, data, index, listSize);
Исправил

2022-04-11 16:14 UTC, Lancoid commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        listSize--;
Нельзя заNULLить `'int'`

2022-04-11 16:15 UTC, Lancoid commented on src/test/java/com/company/skyproeducationspring/list/IntListUnitTest.java
> +        randomGenerator = (new Faker()).random();
Исправил

2022-04-11 20:25 UTC, OKrylov approved these changes
По исправлениям все отлично, замечаний не имею

2022-04-11 20:25 UTC, OKrylov commented on src/main/java/com/company/skyproeducationspring/utils/IntListImpl.java
> +        listSize--;
да, все верно, будет работать только в случае, если все переделаем на Integer (править необязательно)

2022-04-11 20:49 UTC, merged